### ISSUE TITLE
No output when auth missing for rabbitmq

### ISSUE THREAD

**Issue by galan** [galan/plunger#31]
```
Could not connect to server
de.galan.plunger.command.CommandException: Could not connect to server
	at de.galan.plunger.command.rabbitmq.RabbitmqCore.initialize(RabbitmqCore.java:38)
	at de.galan.plunger.command.rabbitmq.RabbitmqCatCommand.initialize(RabbitmqCatCommand.java:38)
	at de.galan.plunger.command.AbstractCommand.execute(AbstractCommand.java:18)
	at de.galan.plunger.application.Client.process(Client.java:36)
	at de.galan.plunger.application.Plunger.start(Plunger.java:62)
	at de.galan.plunger.application.Plunger.main(Plunger.java:37)
Caused by: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:339)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:621)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:648)
	at de.galan.plunger.command.rabbitmq.RabbitmqCore.initialize(RabbitmqCore.java:35)
	... 5 more
```

**Comment by galan** [comment]
Fixed in v1.4
